# This workflow will do a clean install of node dependencies, run tests across different versions of node.

name: Automated Tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        node-version: [22]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          cache-dependency-path: pnpm-lock.yaml
          node-version: ${{ matrix.node-version }}
          check-latest: true
          cache: npm

      - name: Install dependencies
        run: npx pnpm install

      - name: Build project
        run: npx pnpm run build

      - name: Save build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: dist

  test:
    runs-on: ubuntu-latest
    needs: build
    timeout-minutes: 30
    strategy:
      matrix:
        node-version: [22, 20, 18]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: dist

      - name: Install pnpm
        run: npm install -g pnpm yarn

      - name: Pnpm version
        run: pnpm --version

      - name: Yarn version
        run: yarn --version

      - name: Run tests
        run: pnpm test
