# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node

name: Automated Tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        node-version: [22.x, 20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          cache-dependency-path: pnpm-lock.yaml
          node-version: ${{ matrix.node-version }}
          check-latest: true
          cache: "npm"

      - name: Install dependencies
        run: npm install -g pnpm

      - name: Install pnpm
        run: pnpm --silent install

      - name: Run tests
        run: pnpm run test