# This workflow will do a clean install of node dependencies, check the linting and run tests across different versions of node.

name: Automated Tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        node-version: [22]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          cache-dependency-path: pnpm-lock.yaml
          node-version: ${{ matrix.node-version }}
          check-latest: true
          cache: npm

      - name: Install dependencies
        run: npx pnpm install

      - name: Build project
        run: npx pnpm run build

      - name: Save build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: dist

  test:
    runs-on: ubuntu-latest
    needs: build
    timeout-minutes: 30
    strategy:
      matrix:
        node-version: [22, 20, 18, 16]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: dist

      - name: Run tests
        run: |
          if [[ ${{ matrix.node-version }} == 16 ]]; then
            npx pnpm@8 install --prod
            npx pnpm@8 run test
          else
            npx pnpm run test
          fi