# This workflow will do a clean install of node dependencies, run tests across different versions of node.

name: Automated Tests

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        node-version: [22]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: false

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          cache-dependency-path: pnpm-lock.yaml
          node-version: ${{ matrix.node-version }}
          check-latest: true
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: node --run build

      - name: Save build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: dist

  test:
    runs-on: ubuntu-latest
    needs: build
    timeout-minutes: 30
    strategy:
      matrix:
        node-version: [24, 22, 20, 18]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts
          path: dist

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: false

      - name: Check versions
        run: |
          yarn --version
          pnpm --version

      - name: Check global dependencies
        run: |
          npm ls -g --depth=0 --json
          yarn global list --depth=0
          pnpm list -g --depth=0 --json

      - name: Install production dependencies
        run: pnpm install --prod

      - name: Run tests
        if: matrix.node-version < 22
        run: npm run test

      - name: Run tests
        if: matrix.node-version >= 22
        run: node --run test
